// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw8Ve0PprvsVmJ4c8nN6gzw6b26-XLp-c',
    appId: '1:431290043235:android:6b8ea86b42a642136b6156',
    messagingSenderId: '431290043235',
    projectId: 'glitch-77cc6',
    storageBucket: 'glitch-77cc6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDY5PvjlZa_-bcCI1P5l1e70UoOa4eeL5g',
    appId: '1:431290043235:ios:3b08e101a2564a526b6156',
    messagingSenderId: '431290043235',
    projectId: 'glitch-77cc6',
    storageBucket: 'glitch-77cc6.firebasestorage.app',
    iosBundleId: 'com.coderex.glitchAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0d29-VxShzDexLSV0L85glvN_wvESbLI',
    appId: '1:431290043235:web:4ed4d39e9a14b7796b6156',
    messagingSenderId: '431290043235',
    projectId: 'glitch-77cc6',
    authDomain: 'glitch-77cc6.firebaseapp.com',
    storageBucket: 'glitch-77cc6.firebasestorage.app',
    measurementId: 'G-76YZYTNW40',
  );
}
